### ISSUE TITLE
osx firefox lycheejs:// association not set up or not working

### ISSUE THREAD

**Issue by 2075** [Artificial-Engineering/lycheeJS#128] opened 2016-02-17 21:32 UTC
how is this supposed to work? should the protocol be linked manually, system wide or what was the intention here?

if manual: what would be the required steps for user to achieve this? (shouldnt be in future versions)

if automagic: where to fix the binding?

cheers

**Comment by CodeKittey** [comment] 2016-02-17 22:47
There is a one time `open bin/helper/helper.app` call inside the configure script. The helper.app needs to be executed one time, then the helper.sh gets all the lycheejs:// urls

**Comment by cookiengineer** [comment] 2016-02-18 08:00
As @CodeKittey pointed out, there's this in the [configure.sh#L184](https://github.com/Artificial-Engineering/lycheeJS/blob/development/bin/configure.sh#L184) that opens the helper.app initially. That should've integrated the Editor and Ranger with the `lycheejs://` urls.

If you changed stuff in the `helper.applescript` file, you have to [recompile](https://github.com/Artificial-Engineering/lycheeJS/blob/development/bin/helper/osx/compile.sh) it. The applescript file should simply just reroute all lycheejs://* urls to the `./bin/helper.sh $1` and that's it.

For now, the helper is also available via `/usr/bin/lycheejs-helper` after running the `sudo ./bin/configure.sh` script.

The helper is the tool that we need in order for correct process spawning, so it supports the `lycheejs://start=boilerplate`, `lycheejs://stop=boilerplate`, edit, boot and unboot. It also supports the `env:` protocol which allows us to use sandboxed versions of applications in shebangs.

An example file for testing the helper could look like the [harvester.js](https://github.com/Artificial-Engineering/lycheeJS/blob/development/projects/boilerplate/harvester.js#L1) where we use the shebang to have our own self-shipped nodejs binary dependent on the architecture / os etc.

**Comment by cookiengineer** [comment] 2016-02-18 08:06
I forgot: An important note is that all the shell scripts inside `./bin/` use `readlink -f to resolve the lycheejs root directory properly. We need to do this in order to have both `symlink support` from `/usr/bin/*` or `/usr/bin/local/*` and `./bin/woop.sh` calls support.

**Comment by cookiengineer** [comment] 2016-02-18 08:49
I'm not sure, but if I remember correctly there was a problem with Yosemite and unidentifieable Apps. Maybe this will help: http://mac-how-to.wonderhowto.com/how-to/open-third-party-apps-from-unidentified-developers-mac-os-x-0158095/

**Comment by 2075** [comment] 2016-02-18 09:15
ok, when trying this on development, i get a bouquet of errors, will look into it...

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
> Building lycheeJS core and fertilizers
./bin/configure.sh: line 64: /opt/bin/runtime/node/osx/x86_64/node: No such file or directory
./bin/configure.sh: line 66: ./bin/fertilizer.sh: No such file or directory
./bin/configure.sh: line 67: ./bin/fertilizer.sh: No such file or directory
./bin/configure.sh: line 68: ./bin/fertilizer.sh: No such file or directory
./bin/configure.sh: line 69: ./bin/fertilizer.sh: No such file or directory
./bin/configure.sh: line 70: ./bin/fertilizer.sh: No such file or directory
./bin/configure.sh: line 72: ./bin/fertilizer.sh: No such file or directory
./bin/configure.sh: line 73: ./bin/fertilizer.sh: No such file or directory
> DONE
> Fixing chmod rights
find: ./libraries: No such file or directory
find: ./libraries: No such file or directory
find: ./projects: No such file or directory
find: ./projects: No such file or directory
chmod: ./projects/*/harvester.js: No such file or directory
chmod: ./bin: No such file or directory
chmod: -R: No such file or directory
chmod: ./bin/harvester: No such file or directory
chmod: ./bin/breeder.js: No such file or directory
chmod: ./bin/breeder.sh: No such file or directory
chmod: ./bin/configure.js: No such file or directory
chmod: ./bin/editor.sh: No such file or directory
chmod: ./bin/fertilizer.js: No such file or directory
chmod: ./bin/fertilizer.sh: No such file or directory
chmod: ./bin/harvester.js: No such file or directory
chmod: ./bin/harvester.sh: No such file or directory
chmod: ./bin/helper.sh: No such file or directory
chmod: ./bin/ranger.sh: No such file or directory
chmod: ./bin/strainer.js: No such file or directory
chmod: ./bin/strainer.sh: No such file or directory
> DONE
> Integrating GUI Applications
The file /opt/bin/helper/osx/helper.app does not exist.
> DONE
> Integrating CLI Applications
ln: /usr/bin/lycheejs-helper: Operation not permitted
> DONE
```

just a minute...

**Comment by cookiengineer** [comment] 2016-02-18 09:20
It seems as OSX has no `readlink -f` support. We might want to switch to an if/else in the shell scripts. Can you try out changing the `bin/breeder.sh` to something like this:

```bash
#!/bin/bash

LYCHEEJS_ROOT=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $0`;
echo $LYCHEEJS_ROOT;

exit;
```

**Comment by 2075** [comment] 2016-02-18 09:22
yes, mompl, on it already

**Comment by cookiengineer** [comment] 2016-02-18 09:37
I think the clean solution would be using `brew install readlink` and to use `greadlink -f blabla` instead afterwards. I think that is the only clean solution, everything else involves hacky shell scripts that use other interpreted languages and will probably be broken in half a year again.

I'm gonna evaluate if all dependencies are available on macports or homebrew (like binutils, coreutils etc.)

**Comment by 2075** [comment] 2016-02-18 09:44
actually i wanted to propose a brew bottle for lycheejs, but for this case i would not recommend it like this as it requires people to install brew, and some prefer mac ports.

therefore a manual solution like this should be sufficient: [http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac](url)

**Comment by cookiengineer** [comment] 2016-02-18 09:50
The problem is that this will not solve the issue we have. We use `readlink -f` because it follows symlinks, following the paths won't work because `foo/bar` can both link recursively to another structure. Also, the readlink -f behaviour is that you can call the shell script from whereever you want and always have the correct root folder, independent of the `pwd` path.

**Comment by cookiengineer** [comment] 2016-02-23 20:06
Any updates on this? Could it be the case that the `helper.app` must resist in `/Applications` or another folder? Is that allowed or is there a `local` folder available, too?

**Comment by 2075** [comment] 2016-02-23 20:08
will get back to this after the weekend! currently travel + hackathon ;)

**Comment by cookiengineer** [comment] 2016-02-24 21:17
Also, [this](https://trac.macports.org/changeset/63209) is related. I mean, srsly.

**Comment by cookiengineer** [comment] 2016-03-09 09:04
Any updates on this, @2075 ?

I added support for both macports and homebrew in the [netinstall.sh](https://github.com/Artificial-Engineering/lycheeJS-bundle/blob/master/package/netinstall/installer.sh#L47), so that dependencies are installed beforehand. I have no way to test it (lacking an OSX device), so it would be awesome if you could verify the net installer is working.

The installation is made for usage via sudo bash, asking you to press [y] on the Continue question. You can follow up the installation instructions and how it looks like here: https://github.com/Artificial-Engineering/lycheeJS#install-lycheejs

So the working command should be (I uploaded the new Q1 netinstall.sh already):

```bash
sudo bash -c "$(wget -q -O - http://lycheejs.org/download/lycheejs-2016-Q1-netinstall.sh)";
```

I tested it already on Debian, Fedora, Ubuntu and Gentoo, so the detection algorithm seems to work on at least Linux systems. But I don't know if there are any unfixed problems with the default bash / coreutils and/or package names on OSX. I used their websites to figure out the package names, but I have no clue if other problems might occur.

Note that this will probably also solve the readlink issue (but bin/*.sh scripts need to be fixed with an if/else construct) if the installer is working and the `greadlink` binary is available afterwards.

We're planning to do the upcoming release on the weekend, so it would be nice if we had the new installer verified to be working on OSX by then already.

**Comment by cookiengineer** [comment] 2016-03-09 09:09
Note that meanwhile, we moved everything to `/usr/local/bin/lycheejs-*` which means that there should be also the `lycheejs-helper` binary available. Worst case scenario for OSX users would be to start the `lycheejs-ranger` from the command line, then the `html-nwjs` `lychee.ui.entity.Helper` would take in and just execute the `lycheejs-helper` shell script directly without the `lycheejs://` protocol wrapper app.

As we decided to use `/usr/local/bin` and `/opt/lycheejs` among all UNIX installations, we can be sure that the `lycheejs-helper` is always in one of two given paths (using /opt/lycheejs as fallback).

**Comment by cookiengineer** [comment] 2016-03-23 18:19
With the 2016-Q1 Release, this should be fixed but needs evaluation and testing. I'll keep this issue open while waiting for reply from @2075

**Comment by cookiengineer** [comment] 2016-04-10 10:37
Moved to `in-testing` due to inactivity.

**Comment by cookiengineer** [comment] 2016-05-16 10:17
Related issue is #145, so we can close this issue due to lack of initial bug reporter feedback.

**Closed by cookiengineer** 2016-05-16 10:17 UTC
Labels: in-testing, lycheejs-helper
